baseURL = "http://katewalksdogs.netlify.com/"
languageCode = "en-us"
title = "Kate walks dogs"
canonifyUrls = "true"
theme = "landing-page-hugo"

[params]
    description = "in the Inner Richmond, SF"
